### ISSUE TITLE
License change may not be allowed by prior terms

### ISSUE THREAD

**Issue by StaabEng** [NISystemsEngineering/STMMessaging#5]
In the final clause of the old license agreement is the text, "No modification of these Terms shall be effective unless set forth in writing signed by a duly authorized representative of NI." Is user `dsmithni` a duly authorized representative? And how do we record his signature on the change? If not, the change of license appears to be expressly prohibited by the extant terms.

**Comment by cloew-ni** [comment]
This repository of source code is a separate entity from the Simple TCP Messaging reference library that is published on the LabVIEW Tools Network and on ni.com. This new entity is being licensed under the BSD2 license as stated on the main page of the STMMessaging repository and not subject to the agreement or licensing conditions of any other code distribution offered by National Instruments.

**Comment by StaabEng** [comment]
My concern is that commit `b8f9245642115d88e4a3c16f72f19605c092ba14` strapped the NI Source Code license on the code in this repo, and its language states only a duly authorized representative of NI may change the license (in a later commit).

**Comment by cloew-ni** [comment]
Revert commits to remove previous license. Replaced with current BSD license.
