### ISSUE TITLE
Which version of VI Package Manager is required to make changes to the package build spec?

### ISSUE THREAD

**Issue by StaabEng** [NISystemsEngineering/STMMessaging#7]
I see in the .vipb file's XML header that it uses format version 0.5. VIPM 2014 (the current version) uses format version 0.6, so I don't want to edit the file and make a pull request.

**Comment by smithed** [comment]
Thats fine, we're all using VIPM 2014 now so everything else we've released recently has had the 2014 upgrade issue. Its not ideal but since VIPM is free...

->Use VIPM 2014
